### ISSUE TITLE
"Attempt to read property "expiresIn" on null" i am getting this error

### ISSUE THREAD

**Issue by Thanzeer22** [InfyOmLabs/laravel-envato#5]

**Comment by mitulgolakiya** [comment]
@Thanzeer22 can you put some more details and stack trace from which file error is originated and in which operation you are getting this error?

**Comment by Thanzeer22** [comment]
i am getting this error when i am calling API . sir i am new to this can u give me some demo code please

**Comment by mitulgolakiya** [comment]
@Thanzeer22 I think there was a typo in docs here: https://github.com/InfyOmLabs/laravel-envato#load-auth-session

Try with an updated doc and it should work.
